location="eastus"
rg-prefix="rg-multienv-demo"
rg-name="rg-multienv-demo-qa"
storage-account-name="staticwebsite100qa"
index_document="index.html"
source_content="<h1>This is static content coming from the QA Terraform</h1>"